title: lesson-scheduler
description: >- # this means to ignore newlines until "baseurl:"
  A study on backend services applications.

# Build settings
theme: jekyll-theme-minimal
github: [metadata]
baseurl: /lesson-scheduler
plugins:
  - jekyll-feed
