name: Build and merge
on:
  push:
    branches:
      - '*'

jobs:
        
  build:
    name: Build user-service
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B test --file user-service/pom.xml

  sync-branch:
    needs: build
    name: Synch next part
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge part-01 -> part-02
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: part-01-the-application
          target_branch: part-02-the-model-layer
          github_token: ${{ secrets.GITHUB_TOKEN }}