name: Merge
on:
  pull_request:
    branches: '*'

jobs:

  merge:
    name: Merge pull request
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate app token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.8.4
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          MERGE_LABELS: ""
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
